"""
This module was autogenerated by gale.

Every setting here overrides gale.conf.global_settings' default for
gale.game.Game -- anything you remove (or never had) falls back to
gale's own default automatically; see gale.conf for the full list.
You can also add settings of your own here (for instance PLAYER_SPEED)
and read them back the same way, with `from gale.conf import settings`.
"""
import pathlib
from pathlib import Path
import pygame
import json
import os
from gale.timer import Timer

from gale import frames
from gale import input_handler

# No need to call pygame.mixer.init()/pygame.font.init() here: importing
# anything under gale (frames/input_handler above, for instance) already
# calls pygame.init(), which initializes every subsystem pygame ships
# with, mixer and font included -- and does so without raising if, say,
# no audio device is available, unlike calling pygame.mixer.init() directly.

input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_1, 'click')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_q, 'quit')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, 'confirm')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RIGHT, 'right')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_LEFT, 'left')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_o, 'options')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_d, 'right')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_a, 'left')

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_UP, 'up')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_w, 'up')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_DOWN, 'down')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_s, 'down')

# Continuous key
CONTROLS = {
    'left': [pygame.K_LEFT, pygame.K_a],
    'right': [pygame.K_RIGHT, pygame.K_d],
}

TITLE = 'Totemfall'

# Size we want to emulate
VIRTUAL_WIDTH = 480
VIRTUAL_HEIGHT = 270


TILE_SIZE = 16
MAP_WIDTH = 30
TILE_SIZE_Y = 14
MAP_HEIGHT = 19
MAP_RENDER_OFFSET_X = 0
MAP_RENDER_OFFSET_Y = 5

# Size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BASE_DIR = pathlib.Path(__file__).parent

#Prueba se puede borrar -----
raw_obelisk = pygame.image.load(BASE_DIR / "assets" / "graphics" / "Obelisk.png")
scale_factor = 5
new_width = raw_obelisk.get_width() // scale_factor
new_height = raw_obelisk.get_height() // scale_factor
scaled_obelisk = pygame.transform.smoothscale(raw_obelisk, (new_width, new_height))
#-------

raw_dragon = pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprDragon.png")
dragon_scale = 2

new_dragon_w = raw_dragon.get_width() // dragon_scale
new_dragon_h = raw_dragon.get_height() // dragon_scale
scaled_dragon = pygame.transform.smoothscale(raw_dragon, (new_dragon_w, new_dragon_h))
scaled_frame_w = 70 // dragon_scale 
scaled_frame_h = 73 // dragon_scale 

# Register your textures from the graphics folder, for instance:
# TEXTURES = {
#     'my_texture': pygame.image.load(BASE_DIR / "assets" / "graphics" / "my_texture.png")
# }

#UI bar texture
ui_sheet = pygame.image.load(BASE_DIR / "assets" / "graphics" / "UI_Bars.png")

FRAME_RECT = pygame.Rect(197, 135, 86, 15)
FILL_RECT = pygame.Rect(296, 144, 81, 4)

#All textures 
TEXTURES = {
    'xp_frame': ui_sheet.subsurface(FRAME_RECT).copy(),
    'xp_fill': ui_sheet.subsurface(FILL_RECT).copy(),
    'wizard': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprWizard.png"),
    'stairs': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprStairs.png"),
    'cursor': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprCursor.png"),
    'magic_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprMagicBolt.png"),
    'magic_explosion': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprMagicExplosion.png"),
    'batilisk': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk1.png"),
    'attack_swing': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack"/"sprAttackSwing.png"),
    'dragon': scaled_dragon,
    'goblin': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher1.png"),
    'arrow': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack"/"sprArrow.png"),
    'brick': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprBrick.png"),
    'props_swamp': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsSwamp.png"),
    'brimstone': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprBrimstone.png"),
    'props_inferno': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsInferno.png"),
    'lava': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprLava.png"),
    'props_catacombs': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsCatacombs.png"),
    'props_corpses': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsCorpses.png"),
    'rock': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprRock.png"),
    'water': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprWater.png"),
    'heart': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprHeart.png"),
    'sparkle': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprSparkle.png"),
    'sparkle_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprHealParticle.png"),
    'goblin_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher2.png"),
    'goblin_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher3.png"),
    'batilisk_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk2.png"),
    'batilisk_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk3.png"),
    'slime': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium1.png"),
    'slime_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium2.png"),
    'slime_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium3.png"),
    'skeleton': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton1.png"),
    'skeleton_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton2.png"),
    'skeleton_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton3.png"),
    'minotaur': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur1.png"),
    'minotaur_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur2.png"),
    'minotaur_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur3.png"),
    'lizard': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk1.png"),
    'lizard_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk2.png"),
    'lizard_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk3.png"),
    'ghost': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost1.png"),
    'ghost_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost2.png"),
    'ghost_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost3.png"),
    'ghost_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprGhostOrb.png"),
    'fire_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprFireBolt.png"),
    'attack_spear': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprAttackSpear.png"),
    'goblin2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin1.png"),
    'goblin2_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin2.png"),
    'goblin2_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin3.png"),
    'card_base': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base1.png"),
    'card_base_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base20.png"),
    'card_base_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base8.png"),
    'card_base_4': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base17.png"),
    'card_base_5': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base19.png"),
    'card_base_6': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base16.png"),
    'card_base_7': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/ "base18.png"),
    'icon_attack_damage': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "attack_boost.png"),
    'icon_speed_up': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "swiftness.png"),
    'icon_mana_reduce': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "glow.png"),
    'icon_atk_speed_up': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "attack_speed_boost.png"),
    'icon_mana_up': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "mana_up.png"),
    'icon_shoot_speed': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "shoot_speed.png"),
    'icon_regeneration_mana': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "regeneration.png"),
    'icon_heal_totem': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "heal_totem.png"),
    'icon_XP_boost': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "exp_boost.png"),
    'icon_blocks': pygame.image.load(BASE_DIR / "assets" / "graphics" / "cards"/"icons"/ "blocks.png"),
    'xp_orb': pygame.image.load(BASE_DIR / "assets" / "graphics" / "exp_orb.png"),
    'obelisk': scaled_obelisk,
    'menu_bg': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "Fondo.png"),
}

# Register your frames, for instance:
# FRAMES = {
#     'my_frames': frames.generate_frames(TEXTURES['my_texture'], 16, 16)
# }
FRAMES = {
    'wizard_frames': frames.generate_frames(TEXTURES['wizard'], 26, 18),
    'cursor_frames': frames.generate_frames(TEXTURES['cursor'], 45, 45),
    'magic_bolt_frames': frames.generate_frames(TEXTURES['magic_bolt'], 15, 5),
    'magic_explosion_frames': frames.generate_frames(TEXTURES['magic_explosion'], 13, 13),
    'obelisk_frames': frames.generate_frames(TEXTURES['obelisk'], 38, 48),
    'batilisk_frames': frames.generate_frames(TEXTURES['batilisk'], 25,25 ),
    'attack_swing_frames': frames.generate_frames(TEXTURES['attack_swing'], 10, 20),
    'goblin_frames': frames.generate_frames(TEXTURES['goblin'], 20,18 ),
    'arrow_frames': frames.generate_frames(TEXTURES['arrow'], 14,3 ),
    'brick': frames.generate_frames(TEXTURES['brick'], 20, 20),
    'props_swamp': frames.generate_frames(TEXTURES['props_swamp'], 15, 13),
    'brimstone': frames.generate_frames(TEXTURES['brimstone'], 20, 20),
    'props_inferno': frames.generate_frames(TEXTURES['props_inferno'], 11, 15),
    'lava': frames.generate_frames(TEXTURES['lava'], 20, 20),
    'props_catacombs': frames.generate_frames(TEXTURES['props_catacombs'], 16, 21),
    'props_corpses': frames.generate_frames(TEXTURES['props_corpses'], 8, 9),
    'rock': frames.generate_frames(TEXTURES['rock'], 20, 20),
    'dragon_frames': frames.generate_frames(TEXTURES['dragon'], scaled_frame_w, scaled_frame_h),
    'water': frames.generate_frames(TEXTURES['water'], 20, 20),
    'heart_frames': frames.generate_frames(TEXTURES['heart'], 6, 4),
    'sparkle_frames': frames.generate_frames(TEXTURES['sparkle'], 7, 7),
    'sparkle_2_frames': frames.generate_frames(TEXTURES['sparkle_2'], 6, 6),
    'goblin_2_frames': frames.generate_frames(TEXTURES['goblin_2'], 20,18 ),
    'goblin_3_frames': frames.generate_frames(TEXTURES['goblin_3'], 20,18 ),
    'batilisk_2_frames': frames.generate_frames(TEXTURES['batilisk_2'], 25,25 ),
    'batilisk_3_frames': frames.generate_frames(TEXTURES['batilisk_3'], 25,25 ),
    'slime_frames': frames.generate_frames(TEXTURES['slime'], 39,26 ),
    'slime_2_frames': frames.generate_frames(TEXTURES['slime_2'], 39,26 ),
    'slime_3_frames': frames.generate_frames(TEXTURES['slime_3'], 39,26 ),
    'skeleton_frames': frames.generate_frames(TEXTURES['skeleton'], 19,20 ),
    'skeleton_2_frames': frames.generate_frames(TEXTURES['skeleton_2'], 19,20 ),
    'skeleton_3_frames': frames.generate_frames(TEXTURES['skeleton_3'], 19,20 ),
    'minotaur_frames': frames.generate_frames(TEXTURES['minotaur'], 31,24 ),
    'minotaur_2_frames': frames.generate_frames(TEXTURES['minotaur_2'], 31,24 ),
    'minotaur_3_frames': frames.generate_frames(TEXTURES['minotaur_3'], 31,24 ),
    'lizard_frames': frames.generate_frames(TEXTURES['lizard'], 21,20 ),
    'lizard_2_frames': frames.generate_frames(TEXTURES['lizard_2'], 21,20 ),
    'lizard_3_frames': frames.generate_frames(TEXTURES['lizard_3'], 21,20 ),
    'ghost_frames': frames.generate_frames(TEXTURES['ghost'], 19,28 ),
    'ghost_2_frames': frames.generate_frames(TEXTURES['ghost_2'], 19,28 ),
    'ghost_3_frames': frames.generate_frames(TEXTURES['ghost_3'], 19,28 ),
    'ghost_bolt_frames': frames.generate_frames(TEXTURES['ghost_bolt'], 18, 12),
    'fire_bolt_frames': frames.generate_frames(TEXTURES['fire_bolt'], 15, 5),
    'attack_spear_frames': frames.generate_frames(TEXTURES['attack_spear'], 23, 5),
    'goblin2_frames': frames.generate_frames(TEXTURES['goblin2'], 25,25 ),
    'goblin2_2_frames': frames.generate_frames(TEXTURES['goblin2_2'], 25,25 ),
    'goblin2_3_frames': frames.generate_frames(TEXTURES['goblin2_3'], 25,25 ),
    'card_base_frames': frames.generate_frames(TEXTURES['card_base'], 64,96 ),
    'card_base_2_frames': frames.generate_frames(TEXTURES['card_base_2'], 64,96 ),
    'card_base_3_frames': frames.generate_frames(TEXTURES['card_base_3'], 64,96 ),
    'card_base_4_frames': frames.generate_frames(TEXTURES['card_base_4'], 64,96 ),
    'card_base_5_frames': frames.generate_frames(TEXTURES['card_base_5'], 64,96 ),
    'card_base_6_frames': frames.generate_frames(TEXTURES['card_base_6'], 64,96 ),
    'card_base_7_frames': frames.generate_frames(TEXTURES['card_base_7'], 64,96 ),
    'icon_attack_damage_frames': frames.generate_frames(TEXTURES['icon_attack_damage'], 16,16 ),
    'icon_atk_speed_up_frames': frames.generate_frames(TEXTURES['icon_atk_speed_up'], 16,16 ),
    'icon_speed_up_frames': frames.generate_frames(TEXTURES['icon_speed_up'], 16,16 ),
    'icon_mana_up_frames': frames.generate_frames(TEXTURES['icon_mana_up'], 16,16 ),
    'icon_mana_reduce_frames': frames.generate_frames(TEXTURES['icon_mana_reduce'], 16,16 ),
    'icon_shoot_speed_frames': frames.generate_frames(TEXTURES['icon_shoot_speed'], 16,16 ),
    'icon_regeneration_mana_frames': frames.generate_frames(TEXTURES['icon_regeneration_mana'], 16,16 ),
    'icon_heal_totem_frames': frames.generate_frames(TEXTURES['icon_heal_totem'], 16,16 ),
    'icon_XP_boost_frames': frames.generate_frames(TEXTURES['icon_XP_boost'], 16,16 ),
    'icon_blocks_frames': frames.generate_frames(TEXTURES['icon_blocks'], 16,16 ),
    'xp_orb_frames': frames.generate_frames(TEXTURES['xp_orb'], 6, 6),
}

#AudioManager

pygame.mixer.quit()
pygame.mixer.pre_init(44100, -16, 2, 512)
pygame.mixer.init()
pygame.mixer.set_num_channels(32)


class AudioManager:
    def __init__(self):
        self.sounds = {}
        self.sfx_volume = 1.0
        self.music_volume = 1.0
        self.current_song = None
        
    def load_sounds(self, sounds_dict: dict) -> None:
        """Registers the dictionary of Pygame Sound objects."""
        self.sounds = sounds_dict
        self.set_sfx_volume(self.sfx_volume)

    def play_sfx(self, name: str) -> None:
        """Plays a loaded sound effect if it exists in the registry."""
        if name in self.sounds:
            self.sounds[name].play()
            
    def set_sfx_volume(self, volume: float) -> None:
        """Updates the volume (0.0 to 1.0) for all sound effects in memory."""
        self.sfx_volume = max(0.0, min(1.0, volume))
        for sound in self.sounds.values():
            sound.set_volume(self.sfx_volume)
            
    def play_music(self, filepath: str, loops: int = -1, fade_ms: int = 1500) -> None:
        """Streams background music with a built-in Pygame fade-in effect."""
        if self.current_song == filepath:
            return 
            
        self.current_song = filepath
        try:
            pygame.mixer.music.load(filepath)
            pygame.mixer.music.set_volume(self.music_volume)
            pygame.mixer.music.play(loops, fade_ms=fade_ms) 
        except pygame.error as e:
            print(f"Could not load music track: {e}")
            
    def set_music_volume(self, volume: float) -> None:
        """Updates the background music stream volume."""
        self.music_volume = max(0.0, min(1.0, volume))
        pygame.mixer.music.set_volume(self.music_volume)

    def fade_out_and_play(self, next_song_path: str, duration: float = 1.5) -> None:
        """Fades out the current music and uses Gale's Timer to play the next one."""
        if self.current_song == next_song_path:
            return
        fade_ms = int(duration * 1000)
        pygame.mixer.music.fadeout(fade_ms)
        Timer.after(duration, lambda: self.play_music(next_song_path, fade_ms=fade_ms))

    def stop_music_fade(self, duration: float = 1.5) -> None:
        """Silences the music entirely, typically used for Game Over screens."""
        pygame.mixer.music.fadeout(int(duration * 1000))
        self.current_song = None

AUDIO_MANAGER = AudioManager()

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {
    'confirm': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "select_sound.mp3"),
    'hover': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "change_menu.mp3"),
    'hit_enemy': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "hit_enemy.wav"),
    'hit_totem': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "hit_totem.wav"),
    'hit_wall': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "hit_wall.wav"),
    'shoot_wizard': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "shoot_wizard.wav"),
    'exp': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "exp_orb.wav"),
    'spawn_card': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "spawn_card.mp3"),
    'hover_efect': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "hover_efect.wav"),
    'melee': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "melee.wav"),
    'shoot_enemy': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "shoot_enemy.wav"),
    'spawn_ally': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "spawn_ally.wav"),
    'dead_ally': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "dead_ally.wav"),
    'dead_enemy': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "dead_enemy.wav"),
    'chase': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "chase.mp3"),
    'totemfall': pygame.mixer.Sound(BASE_DIR / "assets" / "sounds" / "totemfall.OGG"),
}

AUDIO_MANAGER.load_sounds(SOUNDS)
AUDIO_MANAGER.sounds['shoot_wizard'].set_volume(0.2)
AUDIO_MANAGER.sounds['melee'].set_volume(0.3)
AUDIO_MANAGER.sounds['shoot_enemy'].set_volume(0.5)
AUDIO_MANAGER.sounds['spawn_card'].set_volume(0.5)
AUDIO_MANAGER.sounds['hit_totem'].set_volume(0.5)
AUDIO_MANAGER.sounds['totemfall'].set_volume(0.5)

# Register your fonts from the fonts folder, for instance:
# FONTS = {
#     'small': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "font.ttf", 8)
# }
FONTS = {
    'medium': pygame.font.Font(BASE_DIR / "assets" / "fonts" / "Menu_Font.ttf", 32),
    'small': pygame.font.Font(BASE_DIR / "assets" / "fonts" / "SubMenu_Font.ttf", 16),
    

}

# SAVE SYSTEM
SAVE_FILE = BASE_DIR / "save_data.json"
PLAYER_NAME = None

def load_save_data():
    global PLAYER_NAME
    if os.path.exists(SAVE_FILE):
        with open(SAVE_FILE, 'r') as f:
            data = json.load(f)
            PLAYER_NAME = data.get('player_name', None)

def save_player_name(name: str):
    global PLAYER_NAME
    PLAYER_NAME = name
    with open(SAVE_FILE, 'w') as f:
        json.dump({'player_name': name}, f)

# We load the file as soon as the game starts.
load_save_data()