"""
This module was autogenerated by gale.

Every setting here overrides gale.conf.global_settings' default for
gale.game.Game -- anything you remove (or never had) falls back to
gale's own default automatically; see gale.conf for the full list.
You can also add settings of your own here (for instance PLAYER_SPEED)
and read them back the same way, with `from gale.conf import settings`.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

# No need to call pygame.mixer.init()/pygame.font.init() here: importing
# anything under gale (frames/input_handler above, for instance) already
# calls pygame.init(), which initializes every subsystem pygame ships
# with, mixer and font included -- and does so without raising if, say,
# no audio device is available, unlike calling pygame.mixer.init() directly.

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_q, 'quit')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, 'confirm')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RIGHT, 'right')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_LEFT, 'left')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_o, 'options')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_d, 'right')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_a, 'left')

# Continuous key
CONTROLS = {
    'left': [pygame.K_LEFT, pygame.K_a],
    'right': [pygame.K_RIGHT, pygame.K_d],
}

TITLE = 'Totemfall Game'

# Size we want to emulate
VIRTUAL_WIDTH = 480
VIRTUAL_HEIGHT = 270


TILE_SIZE = 16
MAP_WIDTH = 30
TILE_SIZE_Y = 14
MAP_HEIGHT = 19
MAP_RENDER_OFFSET_X = 0
MAP_RENDER_OFFSET_Y = 5

# Size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BASE_DIR = pathlib.Path(__file__).parent

#Prueba se puede borrar -----
raw_obelisk = pygame.image.load(BASE_DIR / "assets" / "graphics" / "Obelisk.png")
scale_factor = 5
new_width = raw_obelisk.get_width() // scale_factor
new_height = raw_obelisk.get_height() // scale_factor
scaled_obelisk = pygame.transform.smoothscale(raw_obelisk, (new_width, new_height))
#-------



# Register your textures from the graphics folder, for instance:
# TEXTURES = {
#     'my_texture': pygame.image.load(BASE_DIR / "assets" / "graphics" / "my_texture.png")
# }
TEXTURES = {
    'wizard': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprWizard.png"),
    'stairs': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprStairs.png"),
    'cursor': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprCursor.png"),
    'magic_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprMagicBolt.png"),
    'magic_explosion': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprMagicExplosion.png"),
    'batilisk': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk1.png"),
    'attack_swing': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack"/"sprAttackSwing.png"),
    'goblin': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher1.png"),
    'arrow': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack"/"sprArrow.png"),
    'brick': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprBrick.png"),
    'props_swamp': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsSwamp.png"),
    'brimstone': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprBrimstone.png"),
    'props_inferno': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsInferno.png"),
    'lava': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprLava.png"),
    'props_catacombs': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsCatacombs.png"),
    'props_corpses': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprPropsCorpses.png"),
    'rock': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprRock.png"),
    'water': pygame.image.load(BASE_DIR / "assets" / "graphics" / "background" / "sprWater.png"),
    'heart': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprHeart.png"),
    'sparkle': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprSparkle.png"),
    'goblin_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher2.png"),
    'goblin_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters" / "sprOrcArcher3.png"),
    'batilisk_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk2.png"),
    'batilisk_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBatilisk3.png"),
    'slime': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium1.png"),
    'slime_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium2.png"),
    'slime_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprBogslium3.png"),
    'skeleton': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton1.png"),
    'skeleton_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton2.png"),
    'skeleton_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprSkeleton3.png"),
    'minotaur': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur1.png"),
    'minotaur_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur2.png"),
    'minotaur_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprMinotaur3.png"),
    'lizard': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk1.png"),
    'lizard_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk2.png"),
    'lizard_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprLizardMonk3.png"),
    'ghost': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost1.png"),
    'ghost_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost2.png"),
    'ghost_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGhost3.png"),
    'ghost_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprGhostOrb.png"),
    'fire_bolt': pygame.image.load(BASE_DIR / "assets" / "graphics" / "sprFireBolt.png"),
    'attack_spear': pygame.image.load(BASE_DIR / "assets" / "graphics" / "attack" / "sprAttackSpear.png"),
    'goblin2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin1.png"),
    'goblin2_2': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin2.png"),
    'goblin2_3': pygame.image.load(BASE_DIR / "assets" / "graphics" / "monsters"/ "sprGoblin3.png"),
    'obelisk': scaled_obelisk,
}

# Register your frames, for instance:
# FRAMES = {
#     'my_frames': frames.generate_frames(TEXTURES['my_texture'], 16, 16)
# }
FRAMES = {
    'wizard_frames': frames.generate_frames(TEXTURES['wizard'], 26, 18),
    'cursor_frames': frames.generate_frames(TEXTURES['cursor'], 45, 45),
    'magic_bolt_frames': frames.generate_frames(TEXTURES['magic_bolt'], 15, 5),
    'magic_explosion_frames': frames.generate_frames(TEXTURES['magic_explosion'], 13, 13),
    'obelisk_frames': frames.generate_frames(TEXTURES['obelisk'], 38, 48),
    'batilisk_frames': frames.generate_frames(TEXTURES['batilisk'], 25,25 ),
    'attack_swing_frames': frames.generate_frames(TEXTURES['attack_swing'], 10, 20),
    'goblin_frames': frames.generate_frames(TEXTURES['goblin'], 20,18 ),
    'arrow_frames': frames.generate_frames(TEXTURES['arrow'], 14,3 ),
    'brick': frames.generate_frames(TEXTURES['brick'], 20, 20),
    'props_swamp': frames.generate_frames(TEXTURES['props_swamp'], 15, 13),
    'brimstone': frames.generate_frames(TEXTURES['brimstone'], 20, 20),
    'props_inferno': frames.generate_frames(TEXTURES['props_inferno'], 11, 15),
    'lava': frames.generate_frames(TEXTURES['lava'], 20, 20),
    'props_catacombs': frames.generate_frames(TEXTURES['props_catacombs'], 16, 21),
    'props_corpses': frames.generate_frames(TEXTURES['props_corpses'], 8, 9),
    'rock': frames.generate_frames(TEXTURES['rock'], 20, 20),
    'water': frames.generate_frames(TEXTURES['water'], 20, 20),
    'heart_frames': frames.generate_frames(TEXTURES['heart'], 6, 4),
    'sparkle_frames': frames.generate_frames(TEXTURES['sparkle'], 7, 7),
    'goblin_2_frames': frames.generate_frames(TEXTURES['goblin_2'], 20,18 ),
    'goblin_3_frames': frames.generate_frames(TEXTURES['goblin_3'], 20,18 ),
    'batilisk_2_frames': frames.generate_frames(TEXTURES['batilisk_2'], 25,25 ),
    'batilisk_3_frames': frames.generate_frames(TEXTURES['batilisk_3'], 25,25 ),
    'slime_frames': frames.generate_frames(TEXTURES['slime'], 39,26 ),
    'slime_2_frames': frames.generate_frames(TEXTURES['slime_2'], 39,26 ),
    'slime_3_frames': frames.generate_frames(TEXTURES['slime_3'], 39,26 ),
    'skeleton_frames': frames.generate_frames(TEXTURES['skeleton'], 19,20 ),
    'skeleton_2_frames': frames.generate_frames(TEXTURES['skeleton_2'], 19,20 ),
    'skeleton_3_frames': frames.generate_frames(TEXTURES['skeleton_3'], 19,20 ),
    'minotaur_frames': frames.generate_frames(TEXTURES['minotaur'], 31,24 ),
    'minotaur_2_frames': frames.generate_frames(TEXTURES['minotaur_2'], 31,24 ),
    'minotaur_3_frames': frames.generate_frames(TEXTURES['minotaur_3'], 31,24 ),
    'lizard_frames': frames.generate_frames(TEXTURES['lizard'], 21,20 ),
    'lizard_2_frames': frames.generate_frames(TEXTURES['lizard_2'], 21,20 ),
    'lizard_3_frames': frames.generate_frames(TEXTURES['lizard_3'], 21,20 ),
    'ghost_frames': frames.generate_frames(TEXTURES['ghost'], 19,28 ),
    'ghost_2_frames': frames.generate_frames(TEXTURES['ghost_2'], 19,28 ),
    'ghost_3_frames': frames.generate_frames(TEXTURES['ghost_3'], 19,28 ),
    'ghost_bolt_frames': frames.generate_frames(TEXTURES['ghost_bolt'], 18, 12),
    'fire_bolt_frames': frames.generate_frames(TEXTURES['fire_bolt'], 15, 5),
    'attack_spear_frames': frames.generate_frames(TEXTURES['attack_spear'], 23, 5),
    'goblin2_frames': frames.generate_frames(TEXTURES['goblin2'], 25,25 ),
    'goblin2_2_frames': frames.generate_frames(TEXTURES['goblin2_2'], 25,25 ),
    'goblin2_3_frames': frames.generate_frames(TEXTURES['goblin2_3'], 25,25 ),

}

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {}

# Register your fonts from the fonts folder, for instance:
# FONTS = {
#     'small': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "font.ttf", 8)
# }
FONTS = {
    'medium': pygame.font.Font(BASE_DIR / "assets" / "fonts" / "Menu_Font.ttf", 32),
    'small': pygame.font.Font(BASE_DIR / "assets" / "fonts" / "SubMenu_Font.ttf", 16),
    

}
